# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e200e4fba35665bd9df8af77dc7b0735"
name = "shop-b2b-registrations"
application_url = "https://nicholas-chocolate-programmes-notify.trycloudflare.com/"
embedded = true
handle = "codb-2"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_companies,read_customers,read_themes,write_companies,write_content,write_customers,write_online_store_pages,write_themes"

[auth]
redirect_urls = [
  "https://nicholas-chocolate-programmes-notify.trycloudflare.com/auth/callback",
  "https://nicholas-chocolate-programmes-notify.trycloudflare.com/auth/shopify/callback",
  "https://nicholas-chocolate-programmes-notify.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
