# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b84fdd0d836c19d170a35dc0024477d"
name = "shop-b2b-registrations-2"
application_url = "https://shopy-onboard-b2b.onrender.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_companies,read_customers,read_themes,write_companies,write_content,write_customers,write_online_store_pages,write_themes"

[auth]
redirect_urls = [ "https://shopy-onboard-b2b.onrender.com/api/auth" ]
